-- CreateTable
CREATE TABLE "Drink" (
    "drinkId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" STRING NOT NULL,
    "altName" STRING,
    "category" STRING NOT NULL,
    "videoUri" STRING,
    "alcoholic" BOOL NOT NULL DEFAULT true,
    "glassType" STRING NOT NULL,
    "instructions" STRING NOT NULL,

    CONSTRAINT "Drink_pkey" PRIMARY KEY ("drinkId")
);

-- CreateTable
CREATE TABLE "Ingredient" (
    "ingredientId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" STRING NOT NULL,
    "amount" STRING NOT NULL,
    "drinkId" INT4,

    CONSTRAINT "Ingredient_pkey" PRIMARY KEY ("ingredientId")
);

-- AddForeignKey
ALTER TABLE "Ingredient" ADD CONSTRAINT "Ingredient_drinkId_fkey" FOREIGN KEY ("drinkId") REFERENCES "Drink"("drinkId") ON DELETE SET NULL ON UPDATE CASCADE;
