/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DrinkInputType: { // input type
    alcoholic: boolean; // Boolean!
    altName?: string | null; // String
    category: string; // String!
    glassType: string; // String!
    instructions: string; // String!
    name: string; // String!
    videoUri?: string | null; // String
  }
  IngredientInputType: { // input type
    amount: string; // String!
    name: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Drink: { // root type
    alcoholic: boolean; // Boolean!
    altName?: string | null; // String
    category: string; // String!
    drinkId: number; // Int!
    glassType: string; // String!
    instructions: string; // String!
    name: string; // String!
    videoUri?: string | null; // String
  }
  Ingredient: { // root type
    amount: string; // String!
    ingredientId: number; // Int!
    name: string; // String!
  }
  Link: { // root type
    description: string; // String!
    id: number; // Int!
    url: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Drink: { // field return type
    alcoholic: boolean; // Boolean!
    altName: string | null; // String
    category: string; // String!
    drinkId: number; // Int!
    glassType: string; // String!
    ingredients: NexusGenRootTypes['Ingredient'][]; // [Ingredient!]!
    instructions: string; // String!
    name: string; // String!
    videoUri: string | null; // String
  }
  Ingredient: { // field return type
    amount: string; // String!
    ingredientId: number; // Int!
    name: string; // String!
  }
  Link: { // field return type
    description: string; // String!
    id: number; // Int!
    url: string; // String!
  }
  Mutation: { // field return type
    createDrink: NexusGenRootTypes['Drink']; // Drink!
    createIngredient: NexusGenRootTypes['Ingredient']; // Ingredient!
    createPost: NexusGenRootTypes['Link']; // Link!
  }
  Query: { // field return type
    drinks: NexusGenRootTypes['Drink'][]; // [Drink!]!
    feed: NexusGenRootTypes['Link'][]; // [Link!]!
    ingredients: NexusGenRootTypes['Ingredient'][]; // [Ingredient!]!
  }
}

export interface NexusGenFieldTypeNames {
  Drink: { // field return type name
    alcoholic: 'Boolean'
    altName: 'String'
    category: 'String'
    drinkId: 'Int'
    glassType: 'String'
    ingredients: 'Ingredient'
    instructions: 'String'
    name: 'String'
    videoUri: 'String'
  }
  Ingredient: { // field return type name
    amount: 'String'
    ingredientId: 'Int'
    name: 'String'
  }
  Link: { // field return type name
    description: 'String'
    id: 'Int'
    url: 'String'
  }
  Mutation: { // field return type name
    createDrink: 'Drink'
    createIngredient: 'Ingredient'
    createPost: 'Link'
  }
  Query: { // field return type name
    drinks: 'Drink'
    feed: 'Link'
    ingredients: 'Ingredient'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDrink: { // args
      data: NexusGenInputs['DrinkInputType']; // DrinkInputType!
    }
    createIngredient: { // args
      data: NexusGenInputs['IngredientInputType']; // IngredientInputType!
    }
    createPost: { // args
      description: string; // String!
      url: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}